# @package _global_
datamodule:
  _target_: emg2pose.lightning.WindowedEmgDataModule
  window_length: 2_000  # 1 second windows for 2kHz EMG
  val_test_window_length: 10_000  # 20 sec windows for 2kHz EMG
  padding: [0, 0]
  skip_ik_failures: True
