# @package _global_
to_tensor:
  _target_: emg2pose.transforms.ExtractToTensor
  field: emg

transforms:
  train:
    - ${to_tensor}
    - _target_: emg2pose.transforms.RotationAugmentation
  val:
    - ${to_tensor}
  test: ${transforms.val}
