_target_: omen.omen.OMEN
_recursive_: false  # Prevent recursive instantiation

config:
  # Base parameters
  n_variables: 20  # Must be specified
  periodic: null  # Must be specified, or is set to [False] * n_variables
  sessions: null  # must be a list of strings with sessions names
  n_inputs: 64  # must be a list of integers with the number of "channels" for each session
  datashape: B C T
  output_scale_factor: 0.1

  # CAN parameters
  cans:
    module:
      _target_: omen.can.CAN
      N: 48
      beta: 10
      sigma: 0.6
      tau: 1.7
      theta_pad: 0.2

  augmentations:
      temporal_jitter:
        _target_: omen.augmentations.TemporalJitter
        max_shift: 0
        apply: false

  # Portent parameters
  portent:
    _target_: omen.portent.Portent
    activation: relu

    can_heads:
      _target_: omen.modules.MLP
      activation: ${pose_module.decoder.config.portent.activation}
      n_hidden: 256
      n_inputs: ${pose_module.decoder.config.portent.encoder.n_outputs}  # Reference encoding_size
      n_layers: 5
      n_outputs: ${pose_module.decoder.config.cans.module.N}  # Fixed reference
      dropout: 0.0

    encoder:
      _target_: omen.modules.MLP
      activation: ${pose_module.decoder.config.portent.activation}
      n_hidden: 512
      n_inputs: ${pose_module.decoder.config.n_inputs}  # Reference the top-level n_inputs
      n_layers: 5
      n_outputs: 128 
      dropout: 0.0

  # Semantic heads
  semantic_heads:
    module:
      _target_: torch.nn.Identity
    skip: true
